### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security-control#1]
Hello,

I see your username and password. You should remove them from your code !

Regards,
Aurelien

**Comment by samemory** [comment]
Thanks for the catch, didn't mean to make this repo public yet as it's very much a work in progress still.

**Comment by samemory** [comment]
@lenoxys I have fixed the passwords in my repo - can you please delete your fork and re-fork now that I have removed them. It would be greatly appreciated!

**Comment by lenoxys** [comment]
done!
