### ISSUE TITLE
[Bug]: Error - this.driver.refreshData is not a function

### ISSUE THREAD

**Issue by coryforman** [samemory/homebridge-eufy-security-control#258]
### What happened?

I am unable to configure this plugin after reinstalling - anytime I enter my email/password on the configuration screen, I get a red box popup at the lower right hand corder saying:

**Error**

this.driver.refreshData is not a function

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

**Comment by lenoxys** [comment]
Are you sure you're using the latest version ? 1.0.1 or latest beta ?

**Comment by coryforman** [comment]
> i can confirm this is happening with 1.0.0
> 
> ```
>  [EufySecurity] Error refreshing data from Eufy:  TypeError: client.refreshData is not a function
>     at EufySecurityPlatform.refreshData (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:418:22)
>     at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-security/src/platform.ts:424:16)
>     at listOnTimeout (internal/timers.js:555:17)
>     at processTimers (internal/timers.js:498:7)
> ```
> 
> 1.0.1 still not available on homebridge

FYI I just logged in and see an update available for 1.0.2 with a fix for this. Can confirm after updating that the fix resolved it.
