### ISSUE TITLE
With default values of hkOff security state fails

### ISSUE THREAD

**Issue by schliemann** [samemory/homebridge-eufy-security-control#6]
When the homekit security state default mapping is used by omitting them in the configuration the value of 63 is passed to homekit. I assume it should be mapped from the eufy guard mode instead.

This bug will happen for every eufy guard mode bigger than 4.

![59541F81-B13E-4C15-8BF0-E9B45F3DF578](https://user-images.githubusercontent.com/10818044/120722974-12598e00-c4d1-11eb-8ac5-a98d300a0e83.png)

**Comment by samemory** [comment]
Just tested that scenario on mine. Are you running the latest NPM build? 
However, I know the logic is not the best for the mapping. Either way you map it (HK to Eufy or Eufy to HK) there will be a problem because multiple Eufy modes could be tied to the limited HK options. Open to improvements!

![Screenshot 2021-06-03 193049](https://user-images.githubusercontent.com/52178320/120728329-479ab780-c4a2-11eb-9187-590511276112.png)

**Comment by schliemann** [comment]
I actually think you have made some great improvements. I didn't realize you would change this so had been working on the same :).

Will test some more tonight. I haven't installed from the NPM build. I just build you master branch and SCP it to my homebridge device. My config looks like this:

{
            "platform": "EufySecurityControlHomebridgePlugin",
            "name": "@samemory/EufySecurityControlHomebridge",
            "username": "",
            "password": "",
            "pollingIntervalMinutes": 10,
            "enableDetailedLogging": true
        }

**Comment by schliemann** [comment]
Do you have have debug options set? Otherwise the error might not be visible?

**Comment by schliemann** [comment]
Maybe I don't know how to read the config.schema.json. But shouldn't the default values be applied if the section is missing?

As far as I can tell the this.config.hkOff is undefined.

![image](https://user-images.githubusercontent.com/10818044/120866140-9ffbb300-c58f-11eb-8c19-869696d07a92.png)

**Comment by samemory** [comment]
Interesting, I didn’t know that either. Mostly a front end developer myself. When I get some time, I’ll update the code to set a default value, not in the config.

**Comment by samemory** [comment]
Just pushed up a potential fix but won't have time to test it or work anymore on it for another day or two.

**Comment by schliemann** [comment]
I'll take a look latter tonight 👍🏻

**Comment by samemory** [comment]
I think this issue is now fixed.
